# =============================================================================
# TIANSHU tests/base Bazel build
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "object_pool_test",
    srcs = ["object_pool_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "cache_buffer_test",
    srcs = ["cache_buffer_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "spin_lock_test",
    srcs = ["spin_lock_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "rw_lock_test",
    srcs = ["rw_lock_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "sync_test",
    srcs = ["sync_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "atomic_hash_map_test",
    srcs = ["atomic_hash_map_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)
