# =============================================================================
# TIANSHU tests Bazel build
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "hello_test",
    srcs = ["hello_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "object_pool_test",
    srcs = ["object_pool_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)
