# =============================================================================
# TIANSHU tests/sched Bazel build
# =============================================================================

load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "scheduler_test",
    srcs = ["scheduler_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)
