load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "dsl_test",
    srcs = ["dsl_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "sla_test",
    srcs = ["sla_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "slice_state_test",
    srcs = ["slice_state_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)

cc_test(
    name = "record_v2_test",
    srcs = ["record_v2_test.cc"],
    deps = [
        "//tianshu:tianshu",
        "@googletest//:gtest_main",
    ],
    size = "small",
)
