load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    copts = ["-Werror"],
    deps = ["//tianshu:tianshu"],
)

cc_binary(
    name = "intra_example",
    srcs = ["intra_example.cc"],
    deps = ["//tianshu:tianshu"],
)
