add_executable(intra_backend_test intra_backend_test.cc)
target_link_libraries(intra_backend_test PRIVATE tianshu GTest::gtest_main)
gtest_discover_tests(intra_backend_test)

add_executable(transport_registry_test transport_backend_test.cc)
target_link_libraries(transport_registry_test PRIVATE tianshu GTest::gtest_main)
gtest_discover_tests(transport_registry_test)

add_executable(hybrid_transport_test hybrid_transport_test.cc)
target_link_libraries(hybrid_transport_test PRIVATE tianshu GTest::gtest_main)
gtest_discover_tests(hybrid_transport_test)
