// Copyright 2026 Pride Leong.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "tianshu/compiler/codegen.h"

#include <cstddef>
#include <sstream>
#include <string>

#include "tianshu/compiler/ir.h"

namespace tianshu::compiler {
namespace {

// Wire-replay accessor per node kind; sources are driven by the run
// loop, never wired, so they have no entry here.
[[nodiscard]] const char* wire_accessor(const std::string& kind) {
  constexpr const char* kKinds[] = {"map", "join", "op", "stateful", "span", "from", "sink"};
  constexpr const char* kAccessors[] = {"maps",  "joins", "ops",  "statefuls",
                                        "spans", "froms", "sinks"};
  constexpr std::size_t kCount = sizeof(kKinds) / sizeof(kKinds[0]);
  for (std::size_t i = 0; i < kCount; ++i) {
    if (kind == kKinds[i]) {
      return kAccessors[i];
    }
  }
  return nullptr;
}

}  // namespace

std::string generate_source(const IrGraph& graph) {
  const std::string hash = graph.stable_hash();

  std::ostringstream out;
  out << "// Generated by the tianshu L1 pipeline (ADR-0030). Do not edit.\n";
  out << "// flow: " << graph.flow_name() << "  hash: " << hash << "\n";
  out << "// topology (canonical order):\n";
  for (const auto& node : graph.nodes()) {
    out << "//   " << node.topo_order << "  " << node.kind;
    for (const auto& in : node.inputs) {
      out << " " << in;
    }
    if (!node.output.empty()) {
      out << " -> " << node.output;
    }
    out << "\n";
  }
  out << "\n" << R"(#include "tianshu/dsl/dsl_runtime.h")" << "\n\n";
  out << R"(extern "C" const char* tianshu_flow_hash() { return ")" << hash << R"("; })" << "\n\n";
  out << R"(extern "C" void tianshu_flow_install(tianshu::dsl::FlowRuntime* rt,)"
      << "\n";
  out << R"(                                     const tianshu::dsl::Flow* flow) {)"
      << "\n";
  for (const auto& node : graph.nodes()) {
    const char* accessor = wire_accessor(node.kind);
    if (accessor == nullptr) {
      continue;  // source: driven by the run loop
    }
    out << "  flow->" << accessor << "()[" << node.decl_index << "].wire(*rt);\n";
  }
  out << "}\n";
  return out.str();
}

}  // namespace tianshu::compiler
